"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { PLATFORM_LABELS, PLATFORM_DESCRIPTIONS } from "@/lib/platforms";

const MAX_PLATFORMS = 2;

type StrategyData = {
  id: string;
  strategyText: string;
  recommendedPlatforms: string[];
  createdAt: string;
};

type StrategyClientProps = {
  businessId: string;
  locale: string;
  labels: {
    title: string;
    generate: string;
    generating: string;
    generatingStrategy: string;
    recommendedPlatforms: string;
    selectPlatforms: string;
    selectedCount: string;
    contentGenerate: string;
  };
};

function interpolate(s: string, params: Record<string, string | number>): string {
  let out = s;
  for (const [k, v] of Object.entries(params)) {
    out = out.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), String(v));
  }
  return out;
}

export function StrategyClient({ businessId, locale, labels }: StrategyClientProps) {
  const router = useRouter();
  const [strategy, setStrategy] = useState<StrategyData | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoGeneratedRef = useRef(false);

  const isZh = locale === "zh";

  useEffect(() => {
    fetch(`/api/business/${businessId}/strategy`)
      .then((r) => r.json())
      .then((data) => {
        if (data && data.id) setStrategy(data);
      })
      .catch(() => setError("Failed to load"))
      .finally(() => setLoading(false));
  }, [businessId]);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const res = await fetch(`/api/business/${businessId}/strategy`, { method: "POST" });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(data.error ?? "Failed to generate");
        return;
      }
      setStrategy(data);
    } catch {
      setError("Request failed");
    } finally {
      setGenerating(false);
    }
  }

  useEffect(() => {
    if (loading || strategy || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    setGenerating(true);
    setError(null);
    fetch(`/api/business/${businessId}/strategy`, { method: "POST" })
      .then((r) => r.json().catch(() => ({})))
      .then((data) => {
        if (data && data.id) setStrategy(data);
        else setError(data?.error ?? "Failed to generate");
      })
      .catch(() => setError("Request failed"))
      .finally(() => setGenerating(false));
  }, [businessId, loading, strategy]);

  function togglePlatform(key: string) {
    setSelected((prev) => {
      if (prev.includes(key)) return prev.filter((p) => p !== key);
      if (prev.length >= MAX_PLATFORMS) return prev;
      return [...prev, key];
    });
  }

  async function handleContinueToCalendar(e: React.FormEvent) {
    e.preventDefault();
    if (selected.length === 0) return;
    setSaving(true);
    setError(null);
    try {
      await fetch(`/api/business/${businessId}/strategy/confirm`, { method: "POST" });
      const res = await fetch(`/api/business/${businessId}/platforms`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ platforms: selected }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(data.error ?? "Request failed");
        setSaving(false);
        return;
      }
      const calRes = await fetch(`/api/business/${businessId}/calendar/generate`, { method: "POST" });
      await calRes.json().catch(() => ({}));
      router.push(`/dashboard/business/${businessId}/calendar`);
      router.refresh();
    } catch {
      setError("Network error");
    } finally {
      setSaving(false);
    }
  }

  if (loading || (!strategy && generating)) {
    return (
      <div className="mt-6 flex flex-col items-center justify-center gap-3 py-8">
        <p className="text-neutral-500">{labels.generatingStrategy}</p>
      </div>
    );
  }
  if (error && !strategy) {
    return (
      <div className="mt-6 space-y-3">
        <p className="text-red-600 dark:text-red-400">{error}</p>
        <button
          type="button"
          onClick={handleGenerate}
          className="rounded-xl bg-primary-btn px-6 py-2.5 text-sm font-medium text-white transition hover:bg-primary-btn-hover"
        >
          {labels.generate}
        </button>
      </div>
    );
  }
  if (!strategy) {
    return <div className="mt-6 text-neutral-500">{labels.generatingStrategy}</div>;
  }

  const platformOptions = strategy.recommendedPlatforms
    .map((key) => ({
      key,
      label: isZh ? PLATFORM_LABELS[key]?.zh : PLATFORM_LABELS[key]?.en,
      description: isZh ? PLATFORM_DESCRIPTIONS[key]?.zh : PLATFORM_DESCRIPTIONS[key]?.en,
    }))
    .filter((p) => p.label);

  return (
    <div className="mt-6 space-y-5">
      <div className="rounded-lg border border-card-border bg-page-bg p-4">
        <p className="whitespace-pre-wrap text-sm text-foreground">{strategy.strategyText}</p>
      </div>
      <form onSubmit={handleContinueToCalendar}>
        <h2 className="text-sm font-medium text-foreground">{labels.selectPlatforms}</h2>
        <p className="mt-1 text-xs text-neutral-500">{labels.recommendedPlatforms}</p>
        <div className="mt-3 grid gap-4 sm:grid-cols-2">
          {platformOptions.map((opt) => (
            <label
              key={opt.key}
              className={`flex cursor-pointer gap-4 rounded-xl border border-card-border bg-card-bg p-4 shadow-card transition hover:bg-page-bg ${
                selected.includes(opt.key) ? "ring-2 ring-neutral-400 dark:ring-neutral-500" : ""
              } ${!selected.includes(opt.key) && selected.length >= MAX_PLATFORMS ? "opacity-60" : ""}`}
            >
              <input
                type="checkbox"
                checked={selected.includes(opt.key)}
                onChange={() => togglePlatform(opt.key)}
                disabled={!selected.includes(opt.key) && selected.length >= MAX_PLATFORMS}
                className="mt-1 h-4 w-4 rounded border-neutral-300"
              />
              <div>
                <span className="font-medium text-foreground">{opt.label}</span>
                {opt.description && (
                  <p className="mt-0.5 text-sm text-neutral-500">{opt.description}</p>
                )}
              </div>
            </label>
          ))}
        </div>
        <div className="mt-4 flex flex-wrap items-center justify-between gap-4">
          <span className="text-sm text-neutral-500">
            {interpolate(labels.selectedCount, { n: selected.length })}
          </span>
          <button
            type="submit"
            disabled={saving || selected.length === 0}
            className="rounded-xl bg-primary-btn px-6 py-2.5 text-sm font-medium text-white transition hover:bg-primary-btn-hover disabled:opacity-50 dark:text-neutral-900 dark:hover:bg-primary-btn-hover"
          >
            {saving ? "..." : labels.contentGenerate}
          </button>
        </div>
        {error && (
          <p className="mt-3 text-sm text-red-600 dark:text-red-400" role="alert">
            {error}
          </p>
        )}
      </form>
    </div>
  );
}
